# Generated by Django 6.0.7 on 2026-08-08 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('title', models.JSONField()),
                ('kind', models.CharField(choices=[('visit', '내원'), ('remote', '원격')], default='visit', max_length=8)),
                ('status', models.CharField(choices=[('scheduled', '예정'), ('done', '완료'), ('missed', '미방문')], default='scheduled', max_length=10)),
            ],
            options={
                'db_table': 'appointment',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_image', models.ImageField(upload_to='prescriptions/')),
                ('ocr_status', models.CharField(choices=[('pending', '처리 중'), ('done', '완료'), ('failed', '실패')], default='pending', max_length=8)),
                ('ocr_raw', models.JSONField(blank=True, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('timing', models.CharField(blank=True, max_length=20)),
                ('per_day', models.IntegerField(blank=True, null=True)),
                ('total_days', models.IntegerField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
        migrations.CreateModel(
            name='VariableAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'variable_answer',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('drug_name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('dose', models.CharField(blank=True, max_length=20)),
                ('times_per_day', models.CharField(blank=True, max_length=20)),
                ('days', models.CharField(blank=True, max_length=20)),
                ('usage', models.CharField(blank=True, max_length=120)),
                ('is_prn', models.BooleanField(default=False)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='care.prescription')),
            ],
            options={
                'db_table': 'prescription_item',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_date', models.DateField()),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('session_no', models.IntegerField(default=1)),
                ('implant', models.JSONField(blank=True, null=True)),
                ('anesthesia', models.CharField(blank=True, max_length=30)),
                ('surgery_record', models.FileField(blank=True, upload_to='surgery/')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('program_days', models.IntegerField(default=120)),
                ('care_status', models.CharField(choices=[('onboarding', '온보딩 중'), ('active', '진행 중'), ('completed', '완주')], default='onboarding', max_length=12)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgeries', to='accounts.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surgery',
            },
        ),
    ]
