# Generated by Django 6.0.7 on 2026-08-08 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('care', '0001_initial'),
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='procedure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgeries', to='protocols.proceduretype'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='surgeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgeries', to='accounts.clinicstaff'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='surgery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='care.surgery'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='care.surgery'),
        ),
        migrations.AddField(
            model_name='variableanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocols.variablequestion'),
        ),
        migrations.AddField(
            model_name='variableanswer',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_answers', to='care.surgery'),
        ),
        migrations.AlterUniqueTogether(
            name='variableanswer',
            unique_together={('surgery', 'question')},
        ),
    ]
