# Generated by Django 6.0.7 on 2026-08-12 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('care', '0002_initial'),
        ('protocols', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='surgery',
            constraint=models.UniqueConstraint(fields=('patient',), name='one_surgery_per_patient'),
        ),
    ]
