# Generated by Django 6.0.7 on 2026-08-13 15:55

import care.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_surgery_one_surgery_per_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='consult_last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='source_image',
            field=models.ImageField(blank=True, storage=care.models.photo_storage, upload_to='prescriptions/'),
        ),
    ]
