# Generated by Django 6.0.7 on 2026-08-08 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('care', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('patient', '환자'), ('staff', '병원')], max_length=8)),
                ('body_original', models.TextField()),
                ('lang_original', models.CharField(max_length=2)),
                ('body_translated', models.TextField(blank=True)),
                ('lang_translated', models.CharField(blank=True, max_length=2)),
                ('translated_at', models.DateTimeField(blank=True, null=True)),
                ('translation_engine', models.CharField(blank=True, max_length=30)),
                ('attached_label', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attached_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consult_messages', to='reports.recoveryreport')),
                ('sender_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clinicstaff')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consult_messages', to='care.surgery')),
            ],
            options={
                'db_table': 'consult_message',
                'ordering': ['created_at'],
            },
        ),
    ]
