# Generated by Django 6.0.7 on 2026-08-11 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_initial'),
        ('consult', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultmessage',
            name='attached_checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consult_messages', to='checkins.checkin'),
        ),
    ]
