# Generated by Django 6.0.7 on 2026-08-08 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRuleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('name', models.JSONField()),
                ('why', models.JSONField()),
                ('source_text', models.JSONField()),
                ('source_ref', models.CharField(max_length=80)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'activity_rule_template',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRulePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_to', models.IntegerField()),
                ('status', models.CharField(choices=[('no', '금지'), ('care', '주의'), ('ok', '가능')], max_length=4)),
                ('text', models.JSONField()),
                ('order', models.IntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='protocols.activityruletemplate')),
            ],
            options={
                'db_table': 'activity_rule_phase',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.JSONField()),
                ('program_days', models.IntegerField(default=120)),
                ('stage_map', models.JSONField(default=list)),
                ('protocol_version', models.CharField(default='v1.0', max_length=10)),
                ('source_document', models.FileField(blank=True, upload_to='protocols/')),
                ('source_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols', to='accounts.clinic')),
            ],
            options={
                'db_table': 'procedure_type',
            },
        ),
        migrations.AddField(
            model_name='activityruletemplate',
            name='procedure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_templates', to='protocols.proceduretype'),
        ),
        migrations.CreateModel(
            name='CareTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('name', models.JSONField()),
                ('day_from', models.IntegerField()),
                ('day_to', models.IntegerField()),
                ('times_per_day', models.IntegerField(default=1)),
                ('interval_days', models.IntegerField(blank=True, help_text='N일 간격 수행. 채우면 times_per_day보다 우선', null=True)),
                ('why', models.JSONField()),
                ('source_text', models.JSONField()),
                ('source_ref', models.CharField(max_length=80)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('order', models.IntegerField(default=0)),
                ('procedure_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='protocols.proceduretype')),
            ],
            options={
                'db_table': 'care_task_template',
                'ordering': ['order'],
                'unique_together': {('procedure_type', 'key')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='activityruletemplate',
            unique_together={('procedure_type', 'key')},
        ),
        migrations.CreateModel(
            name='VariableQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('question', models.JSONField()),
                ('hint', models.JSONField(blank=True, default=dict)),
                ('answer_type', models.CharField(default='bool', max_length=10)),
                ('effects', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0)),
                ('procedure_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_questions', to='protocols.proceduretype')),
            ],
            options={
                'db_table': 'variable_question',
                'ordering': ['order'],
                'unique_together': {('procedure_type', 'key')},
            },
        ),
    ]
