# Generated by Django 6.0.7 on 2026-08-08 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.JSONField()),
                ('address', models.JSONField(blank=True, default=dict)),
                ('tel', models.CharField(max_length=30)),
                ('reply_hours', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'clinic',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('patient_code', models.CharField(max_length=20, unique=True)),
                ('name', models.JSONField(blank=True, default=dict)),
                ('name_romaji', models.CharField(blank=True, max_length=60)),
                ('nationality', models.CharField(blank=True, max_length=2)),
                ('dob', models.DateField(blank=True, null=True)),
                ('lang', models.CharField(choices=[('ko', '한국어'), ('ja', '日本語'), ('en', 'English')], default='ko', max_length=2)),
                ('lang_locked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='accounts.clinic')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='ClinicStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField()),
                ('name_romaji', models.CharField(max_length=60)),
                ('role', models.CharField(choices=[('director', '원장'), ('intl_coordinator', '국제진료 코디네이터')], max_length=20)),
                ('license_no', models.CharField(blank=True, max_length=40)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.clinic')),
            ],
            options={
                'db_table': 'clinic_staff',
            },
        ),
    ]
