# Generated by Django 6.0.7 on 2026-08-08 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('submission', '제출용 기록'), ('repatriation', '귀국용 요약')], max_length=14)),
                ('lang', models.CharField(max_length=2)),
                ('day_from', models.IntegerField()),
                ('day_to', models.IntegerField()),
                ('body', models.JSONField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('ai_model', models.CharField(blank=True, max_length=40)),
                ('ai_prompt_version', models.CharField(blank=True, max_length=10)),
                ('pdf_file', models.FileField(blank=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='care.surgery')),
            ],
            options={
                'db_table': 'recovery_report',
                'ordering': ['-generated_at'],
            },
        ),
    ]
