# Generated by Django 6.0.7 on 2026-08-08 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('name', models.JSONField()),
                ('medical_term', models.JSONField()),
                ('snomed_code', models.CharField(blank=True, max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'symptom_term',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_key', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('done_count', models.SmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_log',
            },
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('note_lang', models.CharField(blank=True, max_length=2)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='care.surgery')),
            ],
            options={
                'db_table': 'checkin',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CheckinPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.CharField(choices=[('front', '정면'), ('left', '좌측'), ('right', '우측')], max_length=6)),
                ('image', models.ImageField(upload_to='checkins/')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='checkins.checkin')),
            ],
            options={
                'db_table': 'checkin_photo',
            },
        ),
        migrations.CreateModel(
            name='CheckinSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField()),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='checkins.checkin')),
            ],
            options={
                'db_table': 'checkin_symptom',
            },
        ),
    ]
