# Generated by Django 6.0.7 on 2026-08-08 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care', '0001_initial'),
        ('checkins', '0001_initial'),
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomterm',
            name='procedure_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptom_terms', to='protocols.proceduretype'),
        ),
        migrations.AddField(
            model_name='checkinsymptom',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkins.symptomterm'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='care.surgery'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['surgery', 'date'], name='checkin_surgery_147af2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('surgery', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='checkinphoto',
            unique_together={('checkin', 'angle')},
        ),
        migrations.AlterUniqueTogether(
            name='checkinsymptom',
            unique_together={('checkin', 'term')},
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['surgery', 'date'], name='task_log_surgery_8ce87b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasklog',
            unique_together={('surgery', 'task_key', 'date')},
        ),
    ]
