# Generated by Django 6.0.7 on 2026-08-11 12:27

import checkins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinphoto',
            name='image',
            field=models.ImageField(storage=checkins.models.photo_storage, upload_to='checkins/'),
        ),
    ]
